server:
  port: 9999
spring:
  ai:
    mcp:
      client:
        enabled: true
        name: call-mcp-server
                stdio:
                  servers-configuration: classpath:mcp-server.json
        sse:
          connections:
            server1:
              url: http://127.0.0.1:8080
    dashscope:
      api-key: sk-0190e2d62fa949b2b837f374208f402e