spring:
  ai:
    openai:
      api-key: sk-bnkymhvjrgrzuqdoqdivlmuonesfwblqmgvcppginzkmwnnra
      base-url: https://api.siliconflow.cn
      chat:
        options:
          model: deepseek-ai/DeepSeek-V3
    mcp:
      client:
        sse:
          connections:
            server1:
              url: http://localhost:9090
        toolcallback:
          enabled: true
server:
  port: 9091
